// Renders the AI Morning Brief (roll-up across all markets).

import { SENT, esc } from '../format.js';

function sentSpan(s) {
  if (s === 'bull') return `<span class="s gain">${SENT.bull.g}</span>`;
  if (s === 'bear') return `<span class="s loss">${SENT.bear.g}</span>`;
  return `<span class="s" style="color:var(--ink-3)">${SENT.neut.g}</span>`;
}

function whenLabel(asOf) {
  const d = asOf ? new Date(asOf) : new Date();
  const date = new Intl.DateTimeFormat('en-GB', {
    weekday: 'short', day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC',
  }).format(d);
  const time = new Intl.DateTimeFormat('en-GB', {
    hour: '2-digit', minute: '2-digit', timeZone: 'UTC',
  }).format(d);
  return `· ${date} · as of ${time} GMT`;
}

export function renderBrief(el, brief, asOf) {
  if (!brief) { el.innerHTML = ''; return; }
  const lines = (brief.lines || []).map((l) => `
    <div class="bl"><span class="f">${l.flag || ''}</span><span class="m">${esc(l.name)}</span>
      ${sentSpan(l.s)}<span class="tx">${esc(l.text)}</span></div>`).join('');
  const cites = (brief.citations || []).map((c) => `<span class="cite">${esc(c)}</span>`).join('');
  const live = brief.source === 'mock' ? 'mock' : 'Opus 4.8 + live web search';

  el.innerHTML = `
    <div class="brief">
      <div class="eyebrow"><span class="ai">✦</span>AI Morning Brief
        <span class="when">${whenLabel(asOf)}</span></div>
      <p class="lead">${esc(brief.lead)}</p>
      <div class="lines">${lines}</div>
      <div class="hint"><b>Today's hint:</b> ${esc(brief.hint)}</div>
      <div class="cites"><span class="lb">Sources</span>${cites}
        <span class="cite" style="border-style:dashed">+ live web search</span></div>
      <p class="disc" style="margin-top:12px">Generated by AI (${live}) from the market snapshot ·
        Informational only, not investment advice.</p>
    </div>`;
}
